#设置端口
server:
  port: 8082
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND

spring:
  application:
    name: app
  profiles:
    active: api
    include: satoken

